### PR TITLE
3.2.33

### PR DESCRIPTION
**Pull request by tpgxyz**
Update to version 3.2.33, rediff patches and add missing br.
random-seed-location.patch is not needed as it is covered by configs

### CODE REVIEW

**Review by berolinux — APPROVED** [review]
Looks good to me. @abucodonosor may want to take a look as well, not sure what changed upstream between .31 and .32.1...

**Comment by abucodonosor** [comment]
There is now .33 out.

All that looks good, but as I've said on IRC, the random patch should be replaced with a sed line to force that fall back too in case the config is wrong, also configs need to sync.

**Comment by tpgxyz** [comment]
@berolinux  @abucodonosor  configs are synced with distro-release package, which is not yet released as it waits for calamares update second i've updated to 3.2.33 Please merge as it blocks iso building.

**Comment by abucodonosor** [comment]
> @berolinux @abucodonosor configs are synced with distro-release package, which is not yet released as it waits for calamares update second i've updated to 3.2.33 Please merge as it blocks iso building.

Ok, then go ahead and merge that.

**Pull request merged**
